name: Deploy to main

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Switch to main and clean
        run: |
          git checkout main
          git rm -r . || true
          git clean -fdx

      - name: Copy production files from dev
        run: |
          git checkout dev -- custom_components
          git checkout dev -- .github/workflows
          git checkout dev -- hacs.json README.md LICENSE

      - name: Commit changes
        run: |
          git add .
          git commit -m "${{ github.event.head_commit.headline || 'Deploy from dev branch' }}" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Deploy from dev branch"
          title: ${{ github.event.head_commit.headline || 'Deploy from dev branch' }}
          body: ${{ github.event.head_commit.message }}
          base: main
          branch: deploy-to-main-auto
          delete-branch: true
