name: Create Release on main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Calculate next version
        id: next_version
        run: |
          # Simple auto-increment patch version (vX.Y.Z -> vX.Y.(Z+1))
          latest_tag="${{ steps.get_tag.outputs.latest_tag }}"
          if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            next_patch=$((patch+1))
            next_tag="v${major}.${minor}.${next_patch}"
          else
            next_tag="v0.0.1"
          fi
          echo "next_tag=$next_tag" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.next_version.outputs.next_tag }}
          name: Release ${{ steps.next_version.outputs.next_tag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
